stages:
  - build
  - test

pok3rconf:linux:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - linux
  image: fedora
  before_script:
    - dnf install -y gcc gcc-c++ cmake make openssl-devel libusb-devel qt5-qtbase-devel qt5-qtquickcontrols2-devel
  script:
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE="Release" ..
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/pok3rconf
      - build/pok3rtool/pok3rtool
      - build/pok3rtool/libpok3rlib.so
      - build/pok3rtool/rawhid/librawhid.so
      - build/pok3rtool/libchaos/chaos/libchaos.so

test:linux:
  stage: test
  dependencies:
    - pok3rconf:linux
  variables:
    GIT_STRATEGY: none
  tags:
    - linux
  image: fedora
  before_script:
    - dnf install -y libstdc++ openssl libusb qt5-qtbase qt5-qtquickcontrols2
  script:
    - cd build/pok3rtool
    - ./pok3rtool list

